version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
    ports:
      - "${PORT_DB}:5432"